// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8-D2_RuM4k2q23zk_Yxb0aGQsf4OS2cY',
    appId: '1:254050936263:web:efbb99dabde157436ca5e2',
    messagingSenderId: '254050936263',
    projectId: 'fruits-app-1071e',
    authDomain: 'fruits-app-1071e.firebaseapp.com',
    storageBucket: 'fruits-app-1071e.firebasestorage.app',
    measurementId: 'G-2GGBQ2RNRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWJEQCCFMsvbF0HaEwDPFDO6YAKig8HWY',
    appId: '1:254050936263:android:da9d5a766859c0e76ca5e2',
    messagingSenderId: '254050936263',
    projectId: 'fruits-app-1071e',
    storageBucket: 'fruits-app-1071e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0kIPQf-PcbYxU0rR7MDiZuh7xCDm3QjU',
    appId: '1:254050936263:ios:3cd8ca2bfd97c36a6ca5e2',
    messagingSenderId: '254050936263',
    projectId: 'fruits-app-1071e',
    storageBucket: 'fruits-app-1071e.firebasestorage.app',
    iosBundleId: 'com.example.fruitsApp',
  );
}
